name: 'Build from custom environment.yml'
description: 'Build R+Python from custom conda environment.yml'
inputs:
  github-repository:  # id of input
    description: 'Repository name'
    required: false
    default: 'linogaliana/python-datascientist-docker'
  environment-yaml-path:  # id of input
    description: 'Custom environment.yml path'
    required: false
    default: 'environment.yml'
  dockerfile-path:  # id of input
    description: 'Dockerfile path'
    required: false
    default: 'Dockerfile'
  docker-image:  # id of input
    description: 'Docker image on Dockerhub used for publication'
    required: false
    default: 'linogaliana/python-datascientist:latest'
runs:
  using: "composite"
    steps:
      - uses: actions/checkout@v1
      -
        name: Set up QEMU
        if: ${{ github.repository == ${{ inputs.github-repository }} }}
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        if: ${{ github.repository == ${{ inputs.github-repository }} }}
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: ${{ github.repository == ${{ inputs.github-repository }} }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        if: ${{ ${{ inputs.environment-yaml-path }} != "environment.yml" }}
        name: Remove environment.yml if it exists
        run: |
          rm environment.yml
      - 
        name: Rename file
        run: |
          mv ${{ inputs.environment-yaml-path }} environment.yml
      -
        name: Build and push
        if: ${{ github.repository == ${{ inputs.github-repository }} }}
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        with:
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ inputs.docker-image }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
