channels:
  - conda-forge

dependencies:
  - python=3.9
  - GDAL
  - bs4
  - contextily
  - dask
  - descartes
  - folium
  - geopandas
  - geoplot
  - keras
  - plotly
  - poppler-data
  - pytorch
  - python-kaleido
  - tensorflow
  - pip:
    - dash
    - elasticsearch[async]
    - kaleido
    - fasttext
    - graphviz
    - jupyter
    - jupytext
    - jupyter-cache
    - lxml
    - matplotlib
    - nbconvert
    - nltk
    - numpy
    - pandas
    - plotnine
    - py7zr
    - pyarrow>=9.0.0
    - pygeos
    - pyLDAvis>=3.3.1
    - pynsee
    - python-Levenshtein
    - pywaffle
    - rasterio
    - rapidfuzz
    - requests
    - rtree
    - s3fs
    - sentence-transformers
    - scikit-learn>=1.0
    - scikit-image
    - seaborn
    - selenium>=4.11.2
    - spacy>=3.1.0
    - statsmodels
    - tabulate
    - wordcloud
    - xlrd
    - yellowbrick
    - "--editable=git+https://github.com/InseeFrLab/cartiflette@main#egg=cartiflette"
