channels:
  - conda-forge

dependencies:
  - python=3.9
  - GDAL
  - bs4
  - contextily
  - descartes
  - folium
  - geopandas
  - geoplot
  - keras
  - plotly
  - python-kaleido
  - tensorflow
  - pip:
    - dash
    - elasticsearch[async]
    - fasttext
    - jupyter
    - jupytext
    - lxml
    - matplotlib
    - nbconvert
    - nltk
    - numpy
    - pandas
    - pyLDAvis
    - python-Levenshtein
    - pywaffle
    - rasterio
    - rapidfuzz
    - requests
    - rtree
    - scikit-learn>=1.0
    - scikit-image
    - seaborn
    - selenium
    - spacy
    - statsmodels    
    - tabulate    
    - wordcloud
    - xlrd
    - yellowbrick>=1.3
    - "--editable=git+https://github.com/InseeFrLab/Py-Insee-Data@master#egg=pynsee"
