channels:
  - conda-forge

dependencies:
  - python=3.9
  - GDAL
  - bs4
  - contextily
  - descartes
  - folium
  - geopandas
  - plotly
  - pip:
    - jupyter
    - jupytext
    - lxml
    - matplotlib
    - nbconvert
    - numpy
    - pandas
    - rasterio
    - requests
    - rtree
    - tabulate    
    - xlrd
    - "--editable=git+https://github.com/InseeFrLab/Py-Insee-Data@master#egg=pynsee"
