channels:
  - conda-forge

dependencies:
  - python
  - GDAL
  - bs4
  - contextily
  - descartes
  - folium
  - geopandas
  - geoplot
  - keras
  - plotly
  - python-kaleido
  - tensorflow
  - pip:
    - dash
    - fasttext
    - jupyter
    - jupytext
    - matplotlib
    - nbconvert
    - nltk
    - numpy
    - pandas
    - pyLDAvis
    - pywaffle
    - rasterio
    - requests
    - rtree
    - seaborn
    - spacy
    - wordcloud
    - xlrd
    - yellowbrick
