ARG YAML_PATH=environment-manipulation.yml

# Lifehack
FROM ${YAML_PATH} as envirfile

FROM linogaliana/python-datascientist:minimal


# Create the environment:
COPY --from=envirfile environment.yml

RUN cat environment.yml

RUN conda install mamba -n base -c conda-forge && \
    mamba env create --force -q -n python-ENSAE --file environment.yml

RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate python-ENSAE" >> ~/.bashrc


# R packages 
RUN Rscript -e 'devtools::install_github("linogaliana/tablelight", dependencies = TRUE)'

# WRITE RETICULATE_PYTHON VARIABLE IN .Renviron
RUN echo "RETICULATE_PYTHON = '/opt/conda/envs/python-ENSAE/bin/python'" >> /usr/local/lib/R/etc/Renviron
