ARG yaml_path=environment-manipulation.yml
ARG download_nlp=0

# Lifehack
# FROM ${yaml_path} as envirfile

FROM linogaliana/python-datascientist:minimal AS base

# Create the environment:
#COPY --from=envirfile .
COPY ${yaml_path} .
RUN mv ${yaml_path} environment.yml
#COPY environment.yml .

RUN cat environment.yml

RUN conda install mamba -n base -c conda-forge && \
    mamba env create --force -q -n python-ENSAE --file environment.yml

RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate python-ENSAE" >> ~/.bashrc


# R packages 
RUN Rscript -e 'devtools::install_github("linogaliana/tablelight", dependencies = TRUE)'

# WRITE RETICULATE_PYTHON VARIABLE IN .Renviron
RUN echo "RETICULATE_PYTHON = '/opt/conda/envs/python-ENSAE/bin/python'" >> /usr/local/lib/R/etc/Renviron

# ENSURE GOOD PYTHON USED BY COMMAND LINE
RUN alias python='/opt/conda/envs/python-ENSAE/bin/python'
RUN echo "alias python='/opt/conda/envs/python-ENSAE/bin/python'" >> ~/.bashrc
ENV PATH="$PATH:/opt/conda/envs/python-ENSAE/bin/python"


# DOWNLOAD SOME CORPUS FOR NLP ----------------

FROM base AS branch-version-1
RUN echo "downloading corpus"
ENV VAR=TRUE
RUN opt/conda/envs/python-ENSAE/bin/python -m spacy download en_core_web_sm
RUN opt/conda/envs/python-ENSAE/bin/python -m gensim.downloader --download glove-wiki-gigaword-200

FROM base AS branch-version-0
RUN echo "skipping corpus download"
ENV VAR=FALSE

FROM branch-version-${download_nlp} AS final
RUN echo "VAR is equal to ${VAR}"