FROM inseefrlab/vscode-python

USER root

# Create the environment:
COPY environment.yml .

RUN conda install mamba -n base -c conda-forge && \
    mamba env create --force -q -n python-ENSAE --file environment.yml

RUN conda info --envs

RUN echo ". $/anaconda3/etc/profile.d/conda.sh && conda activate python-ENSAE" >> ${HOME}/.bashrc
# Make Python interpreter from "monenv" available
ENV PATH="/miniconda/envs/python-ENSAE/bin:${PATH}"

RUN python -m spacy download en_core_web_sm
RUN python -m gensim.downloader --download glove-wiki-gigaword-200

EXPOSE 5000
CMD ["pip", "freeze"]
